version: "2.3"
services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ./datadir:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017