version: "2.3"
services:
  mongo:
    container_name: mongodb
    image: webhippie/mongodb:latest
    volumes:
      - ./datadir:/var/lib/mongodb
    environment:
      - MONGODB_AUTH=true
      - MONGODB_ROOT_USERNAME=admin
      - MONGODB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
